### PR TITLE
repo: fix redirect after opening/closing milestone

### LINKED ISSUE #5677: Closing/Opening milestone causes 404
**Describe the bug**
When closing or opening an issue milestone, the 302 redirection uses `milestones%3Fstate=closed` and `milestones%3Fstate=open` instead of `milestones?state=closed` and `milestones?state=open`. The milestone is correctly opened or closed though.

**To Reproduce**
1. Go to 'A repository'
1. Click on 'Issues'
1. Click on 'Milestones'
1. Click on 'New Milestone'
1. Set the title and click on 'Create Milestone'
1. Scroll down to 'the new milestone'
1. Click 'Close'
1. Error 404 is displayed

**Expected behavior**
When a milestone is closed or opened, the redirection to the closed or opened milestone page should display the filtered milestones

**Additional context**

- Can you reproduce the bug at https://try.gogs.io:
  - [X] Yes: provide example URL https://try.gogs.io/pj6/test/milestones
  - [ ] No: explain why
- Log gist (usually found in `log/gogs.log`):

Issue experienced in Chrome 70.0.3538.77 and Firefox 66.0.2

### PR DESCRIPTION
**Pull request by afilippov1985**
fixes #5677 

Added `MakeURL` method to `Repository`
`MakeURL` gets `string` or `url.URL` as argument and returns URL prepended with repository URL

### CODE REVIEW

File: internal/context/repo.go [hunk 1]
```diff
@@ -96,6 +97,23 @@ func (r *Repository) GetEditorconfig() (*editorconfig.Editorconfig, error) {
 	return editorconfig.ParseBytes(data)
 }
 
+// MakeURL gets string or url.URL as argument and returns URL prepended with repository URL
+func (r *Repository) MakeURL(location interface{}) string {
+	switch location.(type) {
```
Comment (golangcibot) [inline internal/context/repo.go]: S1034: assigning the result of this type assertion to a variable (switch location := location.(type)) could eliminate the following type assertions:
	internal/context/repo.go:105:29
	internal/context/repo.go:109:14 (from `gosimple`)

File: internal/context/repo.go [hunk 2]
```diff
@@ -96,6 +97,22 @@ func (r *Repository) GetEditorconfig() (*editorconfig.Editorconfig, error) {
 	return editorconfig.ParseBytes(data)
 }
 
+// MakeURL gets string or url.URL as argument and returns URL prepended with repository URL
```
Comment (unknwon) [inline internal/context/repo.go]:
```suggestion
// MakeURL accepts a string or url.URL as argument and returns URL prepended with repository URL.
```

File: internal/route/repo/issue.go [hunk 3]
```diff
@@ -449,7 +448,7 @@ func NewIssuePost(c *context.Context, f form.NewIssue) {
 	}
 
 	log.Trace("Issue created: %d/%d", c.Repo.Repository.ID, issue.ID)
-	c.Redirect(c.Repo.RepoLink + "/issues/" + com.ToStr(issue.Index))
+	c.RawRedirect(c.Repo.MakeURL(fmt.Sprintf("%s/%d", "issues", issue.Index)))
```
Comment (unknwon) [inline internal/route/repo/issue.go]:
```suggestion
	c.RawRedirect(c.Repo.MakeURL(fmt.Sprintf("issues/%d", issue.Index)))
```

File: internal/route/repo/issue.go [hunk 4]
```diff
@@ -522,10 +521,10 @@ func viewIssue(c *context.Context, isPullList bool) {
 
 	// Make sure type and URL matches.
 	if !isPullList && issue.IsPull {
-		c.Redirect(c.Repo.RepoLink + "/pulls/" + com.ToStr(issue.Index))
+		c.RawRedirect(c.Repo.MakeURL(fmt.Sprintf("%s/%d", "pulls", issue.Index)))
```
Comment (unknwon) [inline internal/route/repo/issue.go]:
```suggestion
		c.RawRedirect(c.Repo.MakeURL(fmt.Sprintf("pulls/%d", issue.Index)))
```

File: internal/context/repo.go [hunk 5]
```diff
@@ -96,6 +97,22 @@ func (r *Repository) GetEditorconfig() (*editorconfig.Editorconfig, error) {
...
+	case string:
+		tempURL := url.URL{
+			Path: r.RepoLink + "/" + location,
+		}
+		return tempURL.String()
+	case url.URL:
+		location.Path = r.RepoLink + "/" + location.Path
+		return location.String()
+	default:
+		return r.RepoLink
```
Comment (unknwon) [inline internal/context/repo.go]: I think it should panic, swallow it might cause hard to find bugs.
```suggestion
		panic("location type must be either string or url.URL")
```

File: internal/route/repo/issue.go [hunk 6]
```diff
@@ -522,10 +521,10 @@ func viewIssue(c *context.Context, isPullList bool) {
...
 		return
 	} else if isPullList && !issue.IsPull {
-		c.Redirect(c.Repo.RepoLink + "/issues/" + com.ToStr(issue.Index))
+		c.RawRedirect(c.Repo.MakeURL(fmt.Sprintf("%s/%d", "issues", issue.Index)))
```
Comment (unknwon) [inline internal/route/repo/issue.go]:
```suggestion
		c.RawRedirect(c.Repo.MakeURL(fmt.Sprintf("issues/%d", issue.Index)))
```

File: internal/route/repo/issue.go [hunk 7]
```diff
@@ -850,7 +851,7 @@ func NewComment(c *context.Context, f form.CreateComment) {
 
 	if c.HasError() {
 		c.Flash.Error(c.Data["ErrorMsg"].(string))
-		c.Redirect(fmt.Sprintf("%s/issues/%d", c.Repo.RepoLink, issue.Index))
+		c.RawRedirect(c.Repo.MakeURL(fmt.Sprintf("%s/%d", "issues", issue.Index)))
```
Comment (unknwon) [inline internal/route/repo/issue.go]:
```suggestion
		c.RawRedirect(c.Repo.MakeURL(fmt.Sprintf("issues/%d"", issue.Index)))
```

**Comment by afilippov1985** [comment]
> Quick question: what's the reason you change `c.Redirect` to `c.RawRedirect` even when they don't need to?

`MakeURL` supposed to return properly escaped URLs
`c.Redirect` will do double-escaping
https://github.com/gogs/gogs/blob/91e9495148378ccb2766a63c1e8191d6787fab02/internal/context/context.go#L150

Yes, I know that `c.Redirect` and `c.RawRedirect` will return the same in simple cases like `c.Repo.MakeURL("issues")`
But, for consistency, I replaced all occurrences to `RawRedirect`.

**Comment by unknwon** [comment]
Gotcha, thank you!
